orbs:
  azure-acr: circleci/azure-acr@0.2.0
version: 2.1
workflows:
  build-and-publish-docker-image:
    jobs:
      - azure-acr/build-and-push-image:
          dockerfile: Dockerfile
          login-server-name: revanthacr.azurecr.io
          registry-name: RevanthACR       
          repo: nodejs-webapp
          tag: $CIRCLE_TAG
          filters:
            branches:
              only: master
